development:
   adapter: mysql2
   database: gpt_dev
   username: root
   password: Desarrollo01
   server: localhost
   timeout: 5000

testing:
   adapter: mysql2
   database: freeditorial_test
   username: root
   password: Desarrollo01
   server: localhost
   timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password: