development:
   adapter: mysql2
   database: gpt_dev
   username: root
   password: Desarrollo01
   server: localhost
   timeout: 5000

testing:
   adapter: mysql2
   database: freeditorial_test
   username: root
   password: Desarrollo01
   server: localhost
   timeout: 5000

production:
   adapter: mysql2
   database: freeditorial_prod
   username: root
   password: Desarrollo01
   server: localhost
   timeout: 5000
